"""the shape an extraction fills, and the call that fills it

Docs: https://vedicreader.github.io/varga/schema.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_schema.ipynb.

# %% auto #0
__all__ = ['SCHEMAS', 'FIELD_TYPES', 'EXTRACT_SP', 'Invoice', 'Receipt', 'Catalogue', 'Contract', 'Resume', 'Paper',
           'MeetingNotes', 'Summary', 'dyn_schema', 'as_schema', 'schema_str', 'structured']

# %% ../nbs/01_schema.ipynb #e423da84
import json, re, warnings
from dataclasses import dataclass, fields, is_dataclass, make_dataclass, asdict
from typing import get_origin
from fastcore.all import AttrDict, L

# %% ../nbs/01_schema.ipynb #a125d2cb
@dataclass
class Invoice:
    """An invoice, purchase order or quotation.

    items: one entry per line, each {description, qty, unit_price, amount}.
    Amounts are bare numbers with the currency in `currency`; dates are ISO (2024-03-01).
    """
    number:str = ''
    date:str = ''
    due_date:str = ''
    vendor:str = ''
    vendor_tax_id:str = ''
    bill_to:str = ''
    ship_to:str = ''
    currency:str = ''
    subtotal:float = 0
    tax:float = 0
    total:float = 0
    payment_terms:str = ''
    items:list[dict] = None

# %% ../nbs/01_schema.ipynb #0bb49294
@dataclass
class Receipt:
    """A receipt for a completed payment.

    items: one entry per line, each {description, qty, amount}. `paid_with` is the tender or the
    last digits of the card. Dates are ISO (2024-03-01)."""
    merchant:str = ''
    date:str = ''
    transaction_id:str = ''
    currency:str = ''
    subtotal:float = 0
    tax:float = 0
    total:float = 0
    paid_with:str = ''
    items:list[dict] = None

# %% ../nbs/01_schema.ipynb #5bb4dff8
@dataclass
class Catalogue:
    """A product catalogue, price list or listing page.

    products: one entry per product, each {sku, name, category, price, currency, availability, url}.
    Prices are bare numbers."""
    name:str = ''
    vendor:str = ''
    currency:str = ''
    updated:str = ''
    n_products:int = 0
    products:list[dict] = None

# %% ../nbs/01_schema.ipynb #57fbc6cd
@dataclass
class Contract:
    """An agreement between parties.

    parties: the legal names. obligations: what each side must do. Dates are ISO (2024-03-01)."""
    title:str = ''
    parties:list[str] = None
    effective_date:str = ''
    end_date:str = ''
    term:str = ''
    value:str = ''
    governing_law:str = ''
    termination:str = ''
    obligations:list[str] = None

# %% ../nbs/01_schema.ipynb #24e91acd
@dataclass
class Resume:
    """One person's CV.

    experience: one entry per role, each {employer, title, start, end, summary}.
    education: one entry per qualification, each {institution, qualification, year}."""
    name:str = ''
    email:str = ''
    phone:str = ''
    location:str = ''
    headline:str = ''
    years_experience:float = 0
    skills:list[str] = None
    experience:list[dict] = None
    education:list[dict] = None

# %% ../nbs/01_schema.ipynb #e81c81f6
@dataclass
class Paper:
    """An academic paper. authors: names in order. findings: the claims the paper actually makes."""
    title:str = ''
    authors:list[str] = None
    venue:str = ''
    year:str = ''
    doi:str = ''
    abstract:str = ''
    method:str = ''
    findings:list[str] = None
    limitations:list[str] = None

# %% ../nbs/01_schema.ipynb #17cbf009
@dataclass
class MeetingNotes:
    """Notes from one meeting. actions: one entry per commitment, each {what, owner, due}."""
    title:str = ''
    date:str = ''
    attendees:list[str] = None
    topics:list[str] = None
    decisions:list[str] = None
    actions:list[dict] = None

# %% ../nbs/01_schema.ipynb #70ed9b52
@dataclass
class Summary:
    """What one document says, when no more specific shape fits.

    entities: the organisations, people and places it names. dates: ISO where the document allows."""
    title:str = ''
    doctype:str = ''
    about:str = ''
    key_points:list[str] = None
    entities:list[str] = None
    dates:list[str] = None
    numbers:list[str] = None
    open_questions:list[str] = None

# %% ../nbs/01_schema.ipynb #36192e1e
# PO and quotation share the Invoice schema
SCHEMAS = dict(invoice=Invoice, purchase_order=Invoice, quote=Invoice, receipt=Receipt,
               catalogue=Catalogue, contract=Contract, resume=Resume, paper=Paper,
               meeting_notes=MeetingNotes, other=Summary)

FIELD_TYPES = {'str':str, 'text':str, 'int':int, 'float':float, 'number':float, 'num':float, 'bool':bool,
               'list':list, 'dict':dict, 'strs':list[str], 'dicts':list[dict],
               'list[str]':list[str], 'list[dict]':list[dict]}
_DFLT = {str: '', int: 0, float: 0.0, bool: False}

# %% ../nbs/01_schema.ipynb #7ab433ab
def dyn_schema(spec,                    # 'vendor:str, total:float, items:dicts', or {'vendor':'str'}, or ['vendor']
               name:str='Extracted',    # class name, which the model sees
               doc:str=None,            # class docstring, which the model also sees
) -> type:
    'A dataclass built at runtime from a field spec: the shape of an answer, named in one string.'
    if isinstance(spec, str): spec = [p for p in re.split(r'[,\n]', spec) if p.strip()]
    if isinstance(spec, dict): spec = [f'{k}:{v}' for k, v in spec.items()]
    flds = []
    for p in spec:
        nm, _, ty = (p if isinstance(p, str) else ':'.join(p)).partition(':')
        t = FIELD_TYPES.get(ty.strip().lower() or 'str', str)
        flds.append((re.sub(r'\W', '_', nm.strip()), t, _DFLT.get(t, None)))
    if not flds: raise ValueError(f'no fields in schema spec {spec!r}')
    return make_dataclass(re.sub(r'\W', '', name) or 'Extracted', flds,
                          namespace=dict(__doc__=doc or 'The fields to pull out of the document.'))

# %% ../nbs/01_schema.ipynb #86058550
def as_schema(spec, name:str='Extracted', doc:str=None) -> type:
    'Whatever names a shape, as a dataclass: a `SCHEMAS` key, a dataclass, or a `dyn_schema` spec.'
    if is_dataclass(spec): return spec
    if isinstance(spec, str) and spec.strip() in SCHEMAS: return SCHEMAS[spec.strip()]
    return dyn_schema(spec, name=name, doc=doc)

# %% ../nbs/01_schema.ipynb #393a81bb
def _norm(obj, schema) -> dict:
    "A structured reply as a plain dict, with the `None` a list field defaults to turned back into `[]`."
    d = asdict(obj) if is_dataclass(obj) and not isinstance(obj, type) else dict(obj or {})
    lists = {f.name for f in fields(schema) if f.type is list or get_origin(f.type) is list}
    return {k: ([] if v is None and k in lists else v) for k, v in d.items()}

# %% ../nbs/01_schema.ipynb #d62421fb
def schema_str(schema) -> str:
    "A schema written out for a model to read: its docstring, then `name: type` per field."
    def ty(t):
        if isinstance(t, str): return t
        # `list[dict].__name__` is just 'list'; the parameter is the half the model needs
        return str(t).replace('typing.', '') if get_origin(t) else getattr(t, '__name__', str(t))
    return ((schema.__doc__ or '').strip() + '\n\n{\n'
            + ',\n'.join(f'  "{f.name}": {ty(f.type)}' for f in fields(schema)) + '\n}')

# %% ../nbs/01_schema.ipynb #3dae58c8
def _split_reasoning(text:str) -> str:
    "The answer with any reasoning stripped: rishi's `split_think`, plus the *closing*-only tag an MLX prefill leaves."
    from urai import split_think
    text, _ = split_think(text)
    if '</think>' in text: text = text.partition('</think>')[2]
    return text.strip()

# %% ../nbs/01_schema.ipynb #bf7b950f
def _json_reply(ch, prompt:str, schema, sp:str='') -> object:
    'Ask for the shape as a JSON object in prose and rebuild it, with the model left unconstrained.'
    ch.hist = []
    from urai import resp_text, extract_fence
    txt = resp_text(ch(f'{sp}\n\n{prompt}\n\nReply with only a JSON object in a ```json fence, with '
                       f'exactly these keys and types:\n\n{schema_str(schema)}'))
    d = json.loads(extract_fence(_split_reasoning(txt), 'json'))
    nms = {f.name for f in fields(schema)}
    return schema(**{k: v for k, v in d.items() if k in nms})

# %% ../nbs/01_schema.ipynb #ab344bac
EXTRACT_SP = """You pull structured fields out of one document.

Rules:
- Copy what the document states. Do not compute, convert, round or tidy a value.
- A field the document does not state stays empty. An invented number is worse than a blank one.
- Numbers are bare: 1240.50, not "$1,240.50". The currency belongs in its own field.
- Dates are ISO: 2024-03-01.
- A list field takes every entry the document has, in the order it has them."""


# %% ../nbs/01_schema.ipynb #875af6df
def structured(ch,                # a `rishi.Chat`, e.g. from `new_chat`
               prompt:str,        # the document and the instruction
               schema,            # the dataclass the reply must fill
               sp:str='',         # system prompt for the extraction
) -> dict:
    'A structured reply as a dict, retried as a plain JSON reply when the constrained call fails.'
    try: return _norm(ch.structured(prompt, schema, sp=sp), schema)
    except Exception as e:
        warnings.warn(f'{type(e).__name__} on a constrained call for {schema.__name__} '
                      f'({str(e)[:150]}); retrying as a JSON reply.')
        return _norm(_json_reply(ch, prompt, schema, sp), schema)
